spring.application.name=wordcounter

# Add these to prevent data source errors
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Enable load balancing
spring.cloud.loadbalancer.ribbon.enabled=false

# Coordinator's endpoint
coordinator.url=http://localhost:8080

# Node's own address (configure differently for each instance)
node.address=http://localhost:${server.port}