spring.application.name=wordcounter

server.port=8181

# Add these to prevent data source errors
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Enable load balancing
spring.cloud.loadbalancer.ribbon.enabled=false

# Coordinator's endpoint
coordinator.url=http://localhost:8080

# Node's own address (configure differently for each instance)
node.address=http://localhost:${server.port}

document.path=F:/M.Sc - EAD/3rd Semester/SE5090 - Distributed Computing [2025JAN]/Assignment/document.txt

spring.profiles.active=learner

# Disable gRPC by default
grpc.server.port=0
grpc.server.enabled=false